feb 10th
print("""I am signing up for Replit's 100 days of Python challenge! I will make sure to spend some time everyday coding along, for a minimum of 10 minutes a day. I'll be using Replit, an amazing online IDE so I can do this from my phone wherever I happend to be. No excuses for not coding from the middle of a field!""")
feb 12th
myName = input("What's your name?")
input("Joy")
myage = input("How old are you?")
input("100")
print("Gee, that's REALLY OLD")
replit = input("Do you like Replit? ")
print("no")
print("OF COURSE YOU DO!")
print("oh")
print("So, you are")
print("Joy")
print("and are the ripe old age of")
print("100")
print("and clearly think that Replit is")
print("interesting")
replit = input("How's your Grandma doing? 😘")
print("Why?")
myLunch = input("What are you having for lunch? ")
print("food")
print("Hmm, it sounds like you really should just order")
print("food")
print("as soon as possible!")
print("Definitely not a Phishing Scam")
print("oh")
input("AGUNDALACACA")
print("Thanks for logging in")
print("AGUNDALACACA")
cardNumber = input("What is your credit card number?")
print("Thanks, I definitely wont put")
print("why do you wanna know?")
print("into Amazon and order anything weird")
print("please don't")
print("Promise")
nonya input("What is your Mother's maiden name? ")
print("Why do you want to know?")
print("That's cool, I just wanted to know that")
print("nonya")
print("was your Mum's maiden name. Not because the bank requested it or anything, honest.")
print("Welcome to your adventure simulator. I am going to ask you a bunch of questions and then create an epic story with you as the star!")
name=input("What is your name?")
input("joy")
worst_enemys_name=input("What is your worst enemy's name?")
input("sara")
superpower=input("What's your superpower?")
input("invisibility")
live=input("Where do you live?")
input("london")
food=input("What is your favorite food?")
input("Pizza")
print("Hello Joy! Your ability to become invisible will make sure you never have to look at Sara again. Go eat Pizza as you walk down the streets of London and use Invisibility for good and not evil!")
